version: '3'
services:
  mongodb:
    image: prismagraphql/mongo-single-replica:5.0.3
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:5000"
    depends_on:
      - mongodb
    volumes:
      - mongodb_data:/data/db

volumes:   
  mongodb_data:   